### ISSUE TITLE
.mat file missing

### ISSUE THREAD

**Issue by ARSadri** [Chuqiao2333/Hierarchical_Clustering#1]
Hi,

This issue is about the documentation in the ReadMe file, the mat file is not available here in the repo or anywhere in the link provided in the ReadMe file. Can you please point directory to it? We are interested to re-create the results.

Best regards,
Alireza

**Comment by ARSadri** [comment]
> 

Before you answer, we tried [one of those files](https://zenodo.org/record/5698859/files/03_62kx_CL1p5m_50umapt_spot9_rot15_x512_y5126.npy?download=1)
So I suggest you mention this if this is what is intended. Thanks

**Comment by Chuqiao2333** [comment]
Sorry for the inconvenient and the late response, you can access the .mat file [here](https://drive.google.com/file/d/1H9Sy8IgPXOddjXupLK4bVpNLUOM_ANXa/view?usp=sharing)
